%% read 43 classes traffic sign
    imds1 = imageDatastore('Ahead only', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds2 = imageDatastore('Bend to left', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds3 = imageDatastore('Bend to right', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds4 = imageDatastore('Crossroads', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds5 = imageDatastore('Cycle route ahead', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds6 = imageDatastore('Distance to ‘Give Way’ line ahead', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds7 = imageDatastore('Double bend first to left', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds8 = imageDatastore('End of minimum speed 80', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds9 = imageDatastore('End of no-overtaking zone', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds10 = imageDatastore('End of no-overtaking zone over 3.5t', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds11 = imageDatastore('Keep left', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds12 = imageDatastore('Keep right', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds13 = imageDatastore('Maximum speed 20', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds14 = imageDatastore('Maximum speed 30', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds15 = imageDatastore('Maximum speed 50', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds16 = imageDatastore('Maximum speed 60', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds17 = imageDatastore('Maximum speed 70', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds18 = imageDatastore('Maximum speed 80', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds19 = imageDatastore('Maximum speed 100', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds20 = imageDatastore('Maximum speed 120', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds21 = imageDatastore('Mini-roundabout', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds22 = imageDatastore('National speed limit applies', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds23 = imageDatastore('No entry for vehicular traffic', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds24 = imageDatastore('No overtaking', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds25 = imageDatastore('No overtaking over 3.5t', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds26 = imageDatastore('No vehicle', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds27 = imageDatastore('No vehicles except bicycles being pushed', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds28 = imageDatastore('Other danger', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds29 = imageDatastore('Oxidizing substance', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds30 = imageDatastore('Risk of snow or ice', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds31 = imageDatastore('Road narrows on right', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds32 = imageDatastore('Road works', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds33 = imageDatastore('School crossing patrol ahead', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds34 = imageDatastore('Soft verges', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds35 = imageDatastore('STOP', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds36 = imageDatastore('Traffic signals', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds37 = imageDatastore('Turn left or ahead', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds38 = imageDatastore('Turn right or ahead', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds39 = imageDatastore('Turn left ahead', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds40 = imageDatastore('Turn right ahead', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds41 = imageDatastore('Uneven road', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds42 = imageDatastore('Wild animals', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');
    imds43 = imageDatastore('Zebra crossing', ...
    'IncludeSubfolders',true, ...
    'LabelSource','foldernames');

numimds1 = numel(imds1.Files);
numimds2 = numel(imds2.Files);
numimds3 = numel(imds3.Files);
numimds4 = numel(imds4.Files);
numimds5 = numel(imds5.Files);
numimds6 = numel(imds6.Files);
numimds7 = numel(imds7.Files);
numimds8 = numel(imds8.Files);
numimds9 = numel(imds9.Files);
numimds10 = numel(imds10.Files);
numimds11 = numel(imds11.Files);
numimds12 = numel(imds12.Files);
numimds13 = numel(imds13.Files);
numimds14 = numel(imds14.Files);
numimds15 = numel(imds15.Files);
numimds16 = numel(imds16.Files);
numimds17 = numel(imds17.Files);
numimds18 = numel(imds18.Files);
numimds19 = numel(imds19.Files);
numimds20 = numel(imds20.Files);
numimds21 = numel(imds21.Files);
numimds22 = numel(imds22.Files);
numimds23 = numel(imds23.Files);
numimds24 = numel(imds24.Files);
numimds25 = numel(imds25.Files);
numimds26 = numel(imds26.Files);
numimds27 = numel(imds27.Files);
numimds28 = numel(imds28.Files);
numimds29 = numel(imds29.Files);
numimds30 = numel(imds30.Files);
numimds31 = numel(imds31.Files);
numimds32 = numel(imds32.Files);
numimds33 = numel(imds33.Files);
numimds34 = numel(imds34.Files);
numimds35 = numel(imds35.Files);
numimds36 = numel(imds36.Files);
numimds37 = numel(imds37.Files);
numimds38 = numel(imds38.Files);
numimds39 = numel(imds39.Files);
numimds40 = numel(imds40.Files);
numimds41 = numel(imds41.Files);
numimds42 = numel(imds42.Files);
numimds43 = numel(imds43.Files);
%%calculate total number
a = numimds1+numimds2+numimds3+numimds4+numimds5+numimds6+numimds7+...
numimds8+numimds9+numimds10+numimds11+numimds12+numimds13+numimds14+numimds15+...
numimds16+numimds17+numimds18+numimds19+numimds20+numimds21+numimds22+numimds23+...
numimds24+numimds25+numimds26+numimds27+numimds28+numimds29+numimds30+numimds31+...
numimds32+numimds33+numimds34+numimds35+numimds36+numimds37+numimds38+numimds39+...
numimds40+numimds41+numimds42+numimds43;

%% Comparison between different classes of traffic signs
c = categorical({'00','01','02','03','04',...
    '05','06','07','08','09','10','11',...
    '12','13','14','15','16','17','18',...
    '19','20','21','22','23','24','25',...
    '26','27','28','29','30','31','32',...
    '33','34','35','36','37','38','39',...
    '40','41','42'});
Numbers = [numimds1;numimds2;numimds3;numimds4;numimds5;numimds6;numimds7;...
numimds8;numimds9;numimds10;numimds11;numimds12;numimds13;numimds14;numimds15;...
numimds16;numimds17;numimds18;numimds19;numimds20;numimds21;numimds22;numimds23;...
numimds24;numimds25;numimds26;numimds27;numimds28;numimds29;numimds30;numimds31;...
numimds32;numimds33;numimds34;numimds35;numimds36;numimds37;numimds38;numimds39;...
numimds40;numimds41;numimds42;numimds43];
bar(c,Numbers)
a = (1:size(Numbers,1)).';
x = [a];
for k=1:size(Numbers,1)
    for m = 1:size(Numbers,2)
        text(x(k,m),Numbers(k,m),num2str(Numbers(k,m)),...
            'HorizontalAlignment','center',...
            'VerticalAlignment','bottom')
    end
end
grid on;
title('Numbers of images in different classes in balanced dataset')  
xlabel('Different classes');
ylabel('Number of images');
ylim([0 3000])

















